In [1]:
# coding: utf-8
# наше всё
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams

import prisoner as prs

# настройки pandas, с которыми лучше почти всегда
pd.set_option('display.max_rows', 45000)
pd.set_option('display.max_columns', 50000)
pd.set_option('display.max_colwidth', 5000)

# графики в svg выглядят более четкими
%config InlineBackend.figure_format = 'svg' 
rcParams['figure.figsize'] = 16, 12

In [2]:
prs.standart_tests(3, 5, 0, 1)

First check: Ok
Second check: Ok

In [3]:
prs.make_round(0,1)

(5, 0)

In [4]:
df = pd.read_json('logs_2026-03-28 19:51:09.json', orient='records')
df[0:3]

,timestamp,round,player1,player2,player1_round_score,player2_round_score,player1_total_score,player2_total_score
0,2026-03-28 19:51:01,0,0,0,1,1,1,1
1,2026-03-28 19:51:02,1,0,1,5,0,6,1
2,2026-03-28 19:51:03,2,0,1,5,0,11,1

In [29]:
logs = prs.make_game(
    player1=prs.random_bot, 
    player2=prs.random_bot, 
    max_distance=15
    )

Game over
Player 1 total score: 32
Player 2 total score: 42
Player 2 wins

In [30]:
df = pd.DataFrame(logs)

In [14]:
df.sample(3)

,timestamp,round,player1,player2,player1_round_score,player2_round_score,player1_total_score,player2_total_score
0,2026-03-28 22:25:39,0,1,0,0,5,0,5
2,2026-03-28 22:25:39,2,0,0,1,1,6,6
1,2026-03-28 22:25:39,1,0,1,5,0,5,5

In [36]:
df['game_id'] = 15
game_stat = df.groupby('game_id').agg(
    rounds = ('round', 'count'),
    player1_total_score = ('player1_round_score', 'sum'),
    player2_total_score = ('player2_round_score', 'sum'),
    player1_cooperates = ('player1', lambda x: (x == 1).sum()),
    player2_cooperates = ('player2', lambda x: (x == 1).sum()),
    player1_defects = ('player1', lambda x: (x == 0).sum()),
    player2_defects = ('player2', lambda x: (x == 0).sum()),
).reset_index()
game_stat['player1_round_score_per_round'] = game_stat['player1_total_score'] / game_stat['rounds']
game_stat['player2_round_score_per_round'] = game_stat['player2_total_score'] / game_stat['rounds']
game_stat['player1_cooperates_per_round'] = game_stat['player1_cooperates'] / game_stat['rounds']
game_stat['player2_cooperates_per_round'] = game_stat['player2_cooperates'] / game_stat['rounds']
game_stat['player1_defects_per_round'] = game_stat['player1_defects'] / game_stat['rounds']
game_stat['player2_defects_per_round'] = game_stat['player2_defects'] / game_stat['rounds']
game_stat

,game_id,rounds,player1_total_score,player2_total_score,player1_cooperates,player2_cooperates,player1_defects,player2_defects,player1_round_score_per_round,player2_round_score_per_round,player1_cooperates_per_round,player2_cooperates_per_round,player1_defects_per_round,player2_defects_per_round
0,15,14,32,42,10,8,4,6,2.285714,3.0,0.714286,0.571429,0.285714,0.428571