In [1]:
# coding: utf-8
# наше всё
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams

import prisoner as prs

# настройки pandas, с которыми лучше почти всегда
pd.set_option('display.max_rows', 45000)
pd.set_option('display.max_columns', 50000)
pd.set_option('display.max_colwidth', 5000)

# графики в svg выглядят более четкими
%config InlineBackend.figure_format = 'svg' 
rcParams['figure.figsize'] = 16, 12

In [2]:
prs.standart_tests(3, 5, 0, 1)

First check: Ok
Second check: Ok

In [3]:
prs.make_round(0,1)

(5, 0)

In [4]:
df = pd.read_json('logs_2026-03-28 19:51:09.json', orient='records')

In [5]:
df[0:3]

,timestamp,round,player1,player2,player1_round_score,player2_round_score,player1_total_score,player2_total_score
0,2026-03-28 19:51:01,0,0,0,1,1,1,1
1,2026-03-28 19:51:02,1,0,1,5,0,6,1
2,2026-03-28 19:51:03,2,0,1,5,0,11,1

In [72]:
logs = prs.make_game(
    player1=prs.always_no_bot, 
    player2=prs.random_bot, 
    )

Game over
Player 1 total score: 11
Player 2 total score: 1
Player 1 wins

In [7]:
df = pd.DataFrame(logs)

In [8]:
df

,timestamp,round,player1,player2,player1_round_score,player2_round_score,player1_total_score,player2_total_score
0,2026-03-28 20:38:15,0,1,0,0,5,0,5
1,2026-03-28 20:38:15,1,0,0,1,1,1,6
2,2026-03-28 20:38:15,2,0,0,1,1,2,7
3,2026-03-28 20:38:15,3,0,1,5,0,7,7
4,2026-03-28 20:38:15,4,1,1,3,3,10,10